import type { TextMaterial3D, TextMaterialPreset } from "./types.js";

const material = (
  preset: TextMaterialPreset,
  values: Omit<TextMaterial3D, "preset">,
): TextMaterial3D => ({ preset, ...values });

export const textMaterialPresets: Readonly<Record<TextMaterialPreset, TextMaterial3D>> = {
  clay: material("clay", {
    frontColor: "#8b5cf6",
    sideColor: "#5b21b6",
    metalness: 0.05,
    roughness: 0.62,
    emissive: "#000000",
    emissiveIntensity: 0,
    clearcoat: 0.18,
    clearcoatRoughness: 0.48,
    transmission: 0,
    thickness: 0,
    ior: 1.45,
    iridescence: 0,
  }),
  gold: material("gold", {
    frontColor: "#ffd76a",
    sideColor: "#a96513",
    metalness: 0.92,
    roughness: 0.2,
    emissive: "#000000",
    emissiveIntensity: 0,
    clearcoat: 0.32,
    clearcoatRoughness: 0.16,
    transmission: 0,
    thickness: 0,
    ior: 1.5,
    iridescence: 0,
  }),
  chrome: material("chrome", {
    frontColor: "#f1f5f9",
    sideColor: "#64748b",
    metalness: 1,
    roughness: 0.08,
    emissive: "#000000",
    emissiveIntensity: 0,
    clearcoat: 1,
    clearcoatRoughness: 0.06,
    transmission: 0,
    thickness: 0,
    ior: 1.5,
    iridescence: 0,
  }),
  glass: material("glass", {
    frontColor: "#dff9ff",
    sideColor: "#76c8f5",
    metalness: 0,
    roughness: 0.06,
    emissive: "#000000",
    emissiveIntensity: 0,
    clearcoat: 1,
    clearcoatRoughness: 0.04,
    transmission: 0.94,
    thickness: 1.4,
    ior: 1.52,
    iridescence: 0,
  }),
  neon: material("neon", {
    frontColor: "#ff4fd8",
    sideColor: "#7c3aed",
    metalness: 0.08,
    roughness: 0.24,
    emissive: "#ff16bd",
    emissiveIntensity: 2.8,
    clearcoat: 0.7,
    clearcoatRoughness: 0.14,
    transmission: 0,
    thickness: 0,
    ior: 1.45,
    iridescence: 0,
  }),
  toon: material("toon", {
    frontColor: "#fef08a",
    sideColor: "#f97316",
    metalness: 0,
    roughness: 0.78,
    emissive: "#000000",
    emissiveIntensity: 0,
    clearcoat: 0,
    clearcoatRoughness: 1,
    transmission: 0,
    thickness: 0,
    ior: 1.45,
    iridescence: 0,
  }),
  iridescent: material("iridescent", {
    frontColor: "#b8c8ff",
    sideColor: "#7c3aed",
    metalness: 0.68,
    roughness: 0.16,
    emissive: "#13052b",
    emissiveIntensity: 0.22,
    clearcoat: 1,
    clearcoatRoughness: 0.08,
    transmission: 0,
    thickness: 0.32,
    ior: 1.5,
    iridescence: 1,
  }),
};

export const createTextMaterial3D = (
  preset: TextMaterialPreset,
  overrides: Partial<TextMaterial3D> = {},
): TextMaterial3D => ({
  ...textMaterialPresets[preset],
  ...overrides,
  preset,
});
